# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddWindow(object):
    def setupUi(self, AddWindow):
        AddWindow.setObjectName("AddWindow")
        AddWindow.resize(1100, 1150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddWindow.sizePolicy().hasHeightForWidth())
        AddWindow.setSizePolicy(sizePolicy)
        AddWindow.setMinimumSize(QtCore.QSize(750, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 206, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 206, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        AddWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        AddWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Pictures/Misc/car logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(AddWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(AddWindow)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1080, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dateSelect = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateSelect.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 4), QtCore.QTime(0, 0, 0)))
        self.dateSelect.setCalendarPopup(True)
        self.dateSelect.setObjectName("dateSelect")
        self.gridLayout_2.addWidget(self.dateSelect, 2, 3, 1, 3)
        self.descriptionEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.descriptionEdit.setTabChangesFocus(True)
        self.descriptionEdit.setReadOnly(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout_2.addWidget(self.descriptionEdit, 8, 3, 1, 3)
        self.tagEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.tagEdit.setTabChangesFocus(True)
        self.tagEdit.setObjectName("tagEdit")
        self.gridLayout_2.addWidget(self.tagEdit, 7, 3, 1, 3)
        self.collecteeEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.collecteeEdit.setObjectName("collecteeEdit")
        self.gridLayout_2.addWidget(self.collecteeEdit, 4, 3, 1, 3)
        self.descriptionLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptionLbl.setObjectName("descriptionLbl")
        self.gridLayout_2.addWidget(self.descriptionLbl, 8, 0, 1, 1)
        self.subsystemLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subsystemLbl.setObjectName("subsystemLbl")
        self.gridLayout_2.addWidget(self.subsystemLbl, 5, 0, 1, 1)
        self.collecteeLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.collecteeLbl.setObjectName("collecteeLbl")
        self.gridLayout_2.addWidget(self.collecteeLbl, 4, 0, 1, 1)
        self.nameLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLbl.setObjectName("nameLbl")
        self.gridLayout_2.addWidget(self.nameLbl, 1, 0, 1, 1)
        self.dateLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateLbl.setObjectName("dateLbl")
        self.gridLayout_2.addWidget(self.dateLbl, 2, 0, 1, 1)
        self.fileLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fileLbl.setObjectName("fileLbl")
        self.gridLayout_2.addWidget(self.fileLbl, 9, 0, 1, 1)
        self.fileEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setObjectName("fileEdit")
        self.gridLayout_2.addWidget(self.fileEdit, 9, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 9, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_2.addWidget(self.nameEdit, 1, 3, 1, 3)
        self.subsystemDrop = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.subsystemDrop.setObjectName("subsystemDrop")
        self.gridLayout_2.addWidget(self.subsystemDrop, 5, 3, 1, 3)
        self.projectEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.projectEdit.setObjectName("projectEdit")
        self.gridLayout_2.addWidget(self.projectEdit, 6, 3, 1, 3)
        self.carDrop = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.carDrop.setEditable(True)
        self.carDrop.setObjectName("carDrop")
        self.gridLayout_2.addWidget(self.carDrop, 3, 3, 1, 3)
        self.tagLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tagLbl.setObjectName("tagLbl")
        self.gridLayout_2.addWidget(self.tagLbl, 7, 0, 1, 1)
        self.carLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.carLbl.setObjectName("carLbl")
        self.gridLayout_2.addWidget(self.carLbl, 3, 0, 1, 1)
        self.projectLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.projectLbl.setObjectName("projectLbl")
        self.gridLayout_2.addWidget(self.projectLbl, 6, 0, 1, 1)
        self.fileBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.fileBtn.setObjectName("fileBtn")
        self.gridLayout_2.addWidget(self.fileBtn, 9, 4, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 2, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)
        self.submitBtn = QtWidgets.QPushButton(AddWindow)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout.addWidget(self.submitBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem2)
        self.cancelBtn = QtWidgets.QPushButton(AddWindow)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem3)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.descriptionLbl.setBuddy(self.descriptionEdit)
        self.subsystemLbl.setBuddy(self.subsystemDrop)
        self.collecteeLbl.setBuddy(self.collecteeEdit)
        self.nameLbl.setBuddy(self.nameEdit)
        self.dateLbl.setBuddy(self.dateSelect)
        self.fileLbl.setBuddy(self.fileEdit)
        self.tagLbl.setBuddy(self.tagEdit)
        self.carLbl.setBuddy(self.carDrop)
        self.projectLbl.setBuddy(self.projectEdit)

        self.retranslateUi(AddWindow)
        QtCore.QMetaObject.connectSlotsByName(AddWindow)
        AddWindow.setTabOrder(self.nameEdit, self.dateSelect)
        AddWindow.setTabOrder(self.dateSelect, self.carDrop)
        AddWindow.setTabOrder(self.carDrop, self.collecteeEdit)
        AddWindow.setTabOrder(self.collecteeEdit, self.subsystemDrop)
        AddWindow.setTabOrder(self.subsystemDrop, self.projectEdit)
        AddWindow.setTabOrder(self.projectEdit, self.tagEdit)
        AddWindow.setTabOrder(self.tagEdit, self.descriptionEdit)
        AddWindow.setTabOrder(self.descriptionEdit, self.fileEdit)
        AddWindow.setTabOrder(self.fileEdit, self.submitBtn)
        AddWindow.setTabOrder(self.submitBtn, self.cancelBtn)
        AddWindow.setTabOrder(self.cancelBtn, self.scrollArea)

    def retranslateUi(self, AddWindow):
        _translate = QtCore.QCoreApplication.translate
        AddWindow.setWindowTitle(_translate("AddWindow", "Add Data"))
        self.tagEdit.setPlaceholderText(_translate("AddWindow", "Tags, separated with commas"))
        self.descriptionLbl.setToolTip(_translate("AddWindow", "What is this data?"))
        self.descriptionLbl.setText(_translate("AddWindow", "Description"))
        self.subsystemLbl.setToolTip(_translate("AddWindow", "What team subgroup is this for?"))
        self.subsystemLbl.setText(_translate("AddWindow", "Subsystem"))
        self.collecteeLbl.setToolTip(_translate("AddWindow", "Who Collected the data?"))
        self.collecteeLbl.setText(_translate("AddWindow", "Collectee"))
        self.nameLbl.setToolTip(_translate("AddWindow", "Name for the data"))
        self.nameLbl.setText(_translate("AddWindow", "Name"))
        self.dateLbl.setToolTip(_translate("AddWindow", "When was this data collected?"))
        self.dateLbl.setText(_translate("AddWindow", "Date Collected"))
        self.fileLbl.setToolTip(_translate("AddWindow", "Attatch data file"))
        self.fileLbl.setText(_translate("AddWindow", "Data File"))
        self.tagLbl.setToolTip(_translate("AddWindow", "Tags for data, separate with commas"))
        self.tagLbl.setText(_translate("AddWindow", "Tags"))
        self.carLbl.setToolTip(_translate("AddWindow", "What car was this data collected with/for?"))
        self.carLbl.setText(_translate("AddWindow", "Car Name"))
        self.projectLbl.setToolTip(_translate("AddWindow", "What project is this for?"))
        self.projectLbl.setText(_translate("AddWindow", "Project Name"))
        self.fileBtn.setText(_translate("AddWindow", "Browse"))
        self.submitBtn.setText(_translate("AddWindow", "Submit Data"))
        self.cancelBtn.setText(_translate("AddWindow", "Cancel"))
