# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\detailsUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DetailsWindow(object):
    def setupUi(self, DetailsWindow):
        DetailsWindow.setObjectName("DetailsWindow")
        DetailsWindow.resize(500, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DetailsWindow.sizePolicy().hasHeightForWidth())
        DetailsWindow.setSizePolicy(sizePolicy)
        DetailsWindow.setMinimumSize(QtCore.QSize(500, 600))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 206, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 206, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        DetailsWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        DetailsWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Pictures/Misc/car logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DetailsWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(DetailsWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem)
        self.deleteBtn = QtWidgets.QPushButton(DetailsWindow)
        self.deleteBtn.setObjectName("deleteBtn")
        self.horizontalLayout.addWidget(self.deleteBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)
        self.editBtn = QtWidgets.QPushButton(DetailsWindow)
        self.editBtn.setObjectName("editBtn")
        self.horizontalLayout.addWidget(self.editBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem2)
        self.copyBtn = QtWidgets.QPushButton(DetailsWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.copyBtn.sizePolicy().hasHeightForWidth())
        self.copyBtn.setSizePolicy(sizePolicy)
        self.copyBtn.setObjectName("copyBtn")
        self.horizontalLayout.addWidget(self.copyBtn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem3)
        self.cancelBtn = QtWidgets.QPushButton(DetailsWindow)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(DetailsWindow)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 480, 480))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.subsystemDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.subsystemDisp.setReadOnly(True)
        self.subsystemDisp.setObjectName("subsystemDisp")
        self.gridLayout_2.addWidget(self.subsystemDisp, 5, 2, 1, 1)
        self.nameDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameDisp.setReadOnly(True)
        self.nameDisp.setObjectName("nameDisp")
        self.gridLayout_2.addWidget(self.nameDisp, 1, 2, 1, 1)
        self.descriptionDisp = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.descriptionDisp.setTabChangesFocus(True)
        self.descriptionDisp.setReadOnly(True)
        self.descriptionDisp.setObjectName("descriptionDisp")
        self.gridLayout_2.addWidget(self.descriptionDisp, 9, 2, 1, 1)
        self.fileDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fileDisp.setReadOnly(True)
        self.fileDisp.setObjectName("fileDisp")
        self.gridLayout_2.addWidget(self.fileDisp, 11, 2, 1, 1)
        self.subsystemLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subsystemLbl.setObjectName("subsystemLbl")
        self.gridLayout_2.addWidget(self.subsystemLbl, 5, 0, 1, 1)
        self.descriptionLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptionLbl.setObjectName("descriptionLbl")
        self.gridLayout_2.addWidget(self.descriptionLbl, 9, 0, 1, 1)
        self.dateLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateLbl.setObjectName("dateLbl")
        self.gridLayout_2.addWidget(self.dateLbl, 2, 0, 1, 1)
        self.fileLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fileLbl.setObjectName("fileLbl")
        self.gridLayout_2.addWidget(self.fileLbl, 11, 0, 1, 1)
        self.nameLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLbl.setObjectName("nameLbl")
        self.gridLayout_2.addWidget(self.nameLbl, 1, 0, 1, 1)
        self.projectLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.projectLbl.setObjectName("projectLbl")
        self.gridLayout_2.addWidget(self.projectLbl, 6, 0, 1, 1)
        self.tagLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tagLbl.setObjectName("tagLbl")
        self.gridLayout_2.addWidget(self.tagLbl, 8, 0, 1, 1)
        self.projectDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.projectDisp.setReadOnly(True)
        self.projectDisp.setObjectName("projectDisp")
        self.gridLayout_2.addWidget(self.projectDisp, 6, 2, 1, 1)
        self.carLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.carLbl.setObjectName("carLbl")
        self.gridLayout_2.addWidget(self.carLbl, 3, 0, 1, 1)
        self.tagDisp = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.tagDisp.setTabChangesFocus(True)
        self.tagDisp.setReadOnly(True)
        self.tagDisp.setObjectName("tagDisp")
        self.gridLayout_2.addWidget(self.tagDisp, 8, 2, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 1, 11, 1)
        self.collectorLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.collectorLbl.setObjectName("collectorLbl")
        self.gridLayout_2.addWidget(self.collectorLbl, 4, 0, 1, 1)
        self.dateDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.dateDisp.setReadOnly(True)
        self.dateDisp.setObjectName("dateDisp")
        self.gridLayout_2.addWidget(self.dateDisp, 2, 2, 1, 1)
        self.collectorDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.collectorDisp.setReadOnly(True)
        self.collectorDisp.setObjectName("collectorDisp")
        self.gridLayout_2.addWidget(self.collectorDisp, 4, 2, 1, 1)
        self.carDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.carDisp.setReadOnly(True)
        self.carDisp.setObjectName("carDisp")
        self.gridLayout_2.addWidget(self.carDisp, 3, 2, 1, 1)
        self.testDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.testDisp.setEnabled(True)
        self.testDisp.setReadOnly(True)
        self.testDisp.setObjectName("testDisp")
        self.gridLayout_2.addWidget(self.testDisp, 7, 2, 1, 1)
        self.testLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.testLbl.setObjectName("testLbl")
        self.gridLayout_2.addWidget(self.testLbl, 7, 0, 1, 1)
        self.picLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.picLbl.setObjectName("picLbl")
        self.gridLayout_2.addWidget(self.picLbl, 10, 0, 1, 1)
        self.picDisp = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.picDisp.setReadOnly(True)
        self.picDisp.setObjectName("picDisp")
        self.gridLayout_2.addWidget(self.picDisp, 10, 2, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 2, 1)
        self.descriptionLbl.setBuddy(self.descriptionDisp)
        self.fileLbl.setBuddy(self.fileDisp)
        self.nameLbl.setBuddy(self.nameDisp)
        self.projectLbl.setBuddy(self.projectDisp)
        self.tagLbl.setBuddy(self.tagDisp)
        self.collectorLbl.setBuddy(self.collectorDisp)

        self.retranslateUi(DetailsWindow)
        QtCore.QMetaObject.connectSlotsByName(DetailsWindow)
        DetailsWindow.setTabOrder(self.nameDisp, self.collectorDisp)
        DetailsWindow.setTabOrder(self.collectorDisp, self.projectDisp)
        DetailsWindow.setTabOrder(self.projectDisp, self.tagDisp)
        DetailsWindow.setTabOrder(self.tagDisp, self.descriptionDisp)
        DetailsWindow.setTabOrder(self.descriptionDisp, self.fileDisp)
        DetailsWindow.setTabOrder(self.fileDisp, self.editBtn)
        DetailsWindow.setTabOrder(self.editBtn, self.scrollArea)

    def retranslateUi(self, DetailsWindow):
        _translate = QtCore.QCoreApplication.translate
        DetailsWindow.setWindowTitle(_translate("DetailsWindow", "RIT Baja Database"))
        self.deleteBtn.setText(_translate("DetailsWindow", "Delete Data"))
        self.editBtn.setText(_translate("DetailsWindow", "Edit Data"))
        self.copyBtn.setText(_translate("DetailsWindow", "Save Copy of Data"))
        self.cancelBtn.setText(_translate("DetailsWindow", "Cancel"))
        self.subsystemLbl.setToolTip(_translate("DetailsWindow", "What team subgroup is this for?"))
        self.subsystemLbl.setText(_translate("DetailsWindow", "Subsystem"))
        self.descriptionLbl.setToolTip(_translate("DetailsWindow", "What is this data?"))
        self.descriptionLbl.setText(_translate("DetailsWindow", "Description"))
        self.dateLbl.setToolTip(_translate("DetailsWindow", "When was this data collected?"))
        self.dateLbl.setText(_translate("DetailsWindow", "Date Collected"))
        self.fileLbl.setToolTip(_translate("DetailsWindow", "Attatch data file"))
        self.fileLbl.setText(_translate("DetailsWindow", "Data File(s)"))
        self.nameLbl.setToolTip(_translate("DetailsWindow", "Name for the data"))
        self.nameLbl.setText(_translate("DetailsWindow", "Name"))
        self.projectLbl.setToolTip(_translate("DetailsWindow", "What project is this for?"))
        self.projectLbl.setText(_translate("DetailsWindow", "Project Name"))
        self.tagLbl.setToolTip(_translate("DetailsWindow", "Tags for data, separate with commas"))
        self.tagLbl.setText(_translate("DetailsWindow", "Tags"))
        self.carLbl.setToolTip(_translate("DetailsWindow", "What car was this data collected with/for?"))
        self.carLbl.setText(_translate("DetailsWindow", "Car Name"))
        self.tagDisp.setPlaceholderText(_translate("DetailsWindow", "Tags, separated with commas"))
        self.collectorLbl.setToolTip(_translate("DetailsWindow", "Who Collected the data?"))
        self.collectorLbl.setText(_translate("DetailsWindow", "Collector"))
        self.testLbl.setText(_translate("DetailsWindow", "Test Plan"))
        self.picLbl.setText(_translate("DetailsWindow", "Testing Picture(s)"))


