# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editUI.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EditWindow(object):
    def setupUi(self, EditWindow):
        EditWindow.setObjectName("EditWindow")
        EditWindow.resize(1100, 1150)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EditWindow.sizePolicy().hasHeightForWidth())
        EditWindow.setSizePolicy(sizePolicy)
        EditWindow.setMinimumSize(QtCore.QSize(750, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 206, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 206, 150))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 217, 173))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 109))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 105, 30))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 78, 22))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 157, 45))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        EditWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        EditWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../Pictures/Misc/car logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        EditWindow.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(EditWindow)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem)
        self.submitBtn = QtWidgets.QPushButton(EditWindow)
        self.submitBtn.setObjectName("submitBtn")
        self.horizontalLayout.addWidget(self.submitBtn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem1)
        self.cancelBtn = QtWidgets.QPushButton(EditWindow)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(EditWindow)
        self.scrollArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1080, 749))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.carDrop = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.carDrop.setEditable(True)
        self.carDrop.setObjectName("carDrop")
        self.gridLayout_2.addWidget(self.carDrop, 4, 3, 1, 3)
        self.carLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.carLbl.setObjectName("carLbl")
        self.gridLayout_2.addWidget(self.carLbl, 4, 0, 1, 1)
        self.projectLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.projectLbl.setObjectName("projectLbl")
        self.gridLayout_2.addWidget(self.projectLbl, 7, 0, 1, 1)
        self.tagLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.tagLbl.setObjectName("tagLbl")
        self.gridLayout_2.addWidget(self.tagLbl, 8, 0, 1, 1)
        self.dateSelect = QtWidgets.QDateEdit(self.scrollAreaWidgetContents)
        self.dateSelect.setDateTime(QtCore.QDateTime(QtCore.QDate(2019, 7, 4), QtCore.QTime(0, 0, 0)))
        self.dateSelect.setCalendarPopup(True)
        self.dateSelect.setObjectName("dateSelect")
        self.gridLayout_2.addWidget(self.dateSelect, 3, 3, 1, 3)
        self.descriptionEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.descriptionEdit.setTabChangesFocus(True)
        self.descriptionEdit.setReadOnly(False)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.gridLayout_2.addWidget(self.descriptionEdit, 9, 3, 1, 3)
        self.tagEdit = QtWidgets.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.tagEdit.setTabChangesFocus(True)
        self.tagEdit.setObjectName("tagEdit")
        self.gridLayout_2.addWidget(self.tagEdit, 8, 3, 1, 3)
        self.descriptionLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.descriptionLbl.setObjectName("descriptionLbl")
        self.gridLayout_2.addWidget(self.descriptionLbl, 9, 0, 1, 1)
        self.subsystemLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.subsystemLbl.setObjectName("subsystemLbl")
        self.gridLayout_2.addWidget(self.subsystemLbl, 6, 0, 1, 1)
        self.collectorEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.collectorEdit.setObjectName("collectorEdit")
        self.gridLayout_2.addWidget(self.collectorEdit, 5, 3, 1, 3)
        self.nameLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.nameLbl.setObjectName("nameLbl")
        self.gridLayout_2.addWidget(self.nameLbl, 2, 0, 1, 1)
        self.dateLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dateLbl.setObjectName("dateLbl")
        self.gridLayout_2.addWidget(self.dateLbl, 3, 0, 1, 1)
        self.fileLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.fileLbl.setObjectName("fileLbl")
        self.gridLayout_2.addWidget(self.fileLbl, 10, 0, 1, 1)
        self.fileEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.fileEdit.setReadOnly(True)
        self.fileEdit.setObjectName("fileEdit")
        self.gridLayout_2.addWidget(self.fileEdit, 10, 3, 1, 1)
        self.collectorLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.collectorLbl.setObjectName("collectorLbl")
        self.gridLayout_2.addWidget(self.collectorLbl, 5, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 2, 1, 9, 1)
        self.projectEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.projectEdit.setObjectName("projectEdit")
        self.gridLayout_2.addWidget(self.projectEdit, 7, 3, 1, 3)
        self.subsystemDrop = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.subsystemDrop.setObjectName("subsystemDrop")
        self.gridLayout_2.addWidget(self.subsystemDrop, 6, 3, 1, 3)
        self.nameEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.nameEdit.setObjectName("nameEdit")
        self.gridLayout_2.addWidget(self.nameEdit, 2, 3, 1, 3)
        self.requiredLbl = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.requiredLbl.setFont(font)
        self.requiredLbl.setAlignment(QtCore.Qt.AlignCenter)
        self.requiredLbl.setObjectName("requiredLbl")
        self.gridLayout_2.addWidget(self.requiredLbl, 1, 0, 1, 5)
        self.fileBtn = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.fileBtn.setObjectName("fileBtn")
        self.gridLayout_2.addWidget(self.fileBtn, 10, 4, 1, 2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 1, 0, 2, 1)
        self.carLbl.setBuddy(self.carDrop)
        self.projectLbl.setBuddy(self.projectEdit)
        self.tagLbl.setBuddy(self.tagEdit)
        self.descriptionLbl.setBuddy(self.descriptionEdit)
        self.subsystemLbl.setBuddy(self.subsystemDrop)
        self.nameLbl.setBuddy(self.nameEdit)
        self.dateLbl.setBuddy(self.dateSelect)
        self.fileLbl.setBuddy(self.fileEdit)
        self.collectorLbl.setBuddy(self.collectorEdit)

        self.retranslateUi(EditWindow)
        QtCore.QMetaObject.connectSlotsByName(EditWindow)
        EditWindow.setTabOrder(self.nameEdit, self.dateSelect)
        EditWindow.setTabOrder(self.dateSelect, self.carDrop)
        EditWindow.setTabOrder(self.carDrop, self.collectorEdit)
        EditWindow.setTabOrder(self.collectorEdit, self.subsystemDrop)
        EditWindow.setTabOrder(self.subsystemDrop, self.projectEdit)
        EditWindow.setTabOrder(self.projectEdit, self.tagEdit)
        EditWindow.setTabOrder(self.tagEdit, self.descriptionEdit)
        EditWindow.setTabOrder(self.descriptionEdit, self.fileEdit)
        EditWindow.setTabOrder(self.fileEdit, self.submitBtn)
        EditWindow.setTabOrder(self.submitBtn, self.cancelBtn)
        EditWindow.setTabOrder(self.cancelBtn, self.scrollArea)

    def retranslateUi(self, EditWindow):
        _translate = QtCore.QCoreApplication.translate
        EditWindow.setWindowTitle(_translate("EditWindow", "RIT Baja Database"))
        self.submitBtn.setText(_translate("EditWindow", "Submit Data"))
        self.cancelBtn.setText(_translate("EditWindow", "Cancel"))
        self.carLbl.setToolTip(_translate("EditWindow", "What car was this data collected with/for?"))
        self.carLbl.setText(_translate("EditWindow", "Car Name"))
        self.projectLbl.setToolTip(_translate("EditWindow", "What project is this for?"))
        self.projectLbl.setText(_translate("EditWindow", "Project Name"))
        self.tagLbl.setToolTip(_translate("EditWindow", "Tags for data, separate with commas"))
        self.tagLbl.setText(_translate("EditWindow", "Tags"))
        self.tagEdit.setPlaceholderText(_translate("EditWindow", "Tags, separated with commas"))
        self.descriptionLbl.setToolTip(_translate("EditWindow", "What is this data?"))
        self.descriptionLbl.setText(_translate("EditWindow", "Description**"))
        self.subsystemLbl.setToolTip(_translate("EditWindow", "What team subgroup is this for?"))
        self.subsystemLbl.setText(_translate("EditWindow", "Subsystem**"))
        self.nameLbl.setToolTip(_translate("EditWindow", "Name for the data"))
        self.nameLbl.setText(_translate("EditWindow", "Name**"))
        self.dateLbl.setToolTip(_translate("EditWindow", "When was this data collected?"))
        self.dateLbl.setText(_translate("EditWindow", "Date Collected**"))
        self.fileLbl.setToolTip(_translate("EditWindow", "Attatch data file"))
        self.fileLbl.setText(_translate("EditWindow", "Data File(s)**"))
        self.collectorLbl.setToolTip(_translate("EditWindow", "Who Collected the data?"))
        self.collectorLbl.setText(_translate("EditWindow", "Collector"))
        self.requiredLbl.setText(_translate("EditWindow", "fields marked with a ** are required"))
        self.fileBtn.setText(_translate("EditWindow", "Browse"))
